__include__: [
  '../dataset/lmot_dark_tracking.yml',
  '../runtime.yml',
  './include/dataloader_colorJit_affine_perspective.yml',
  './include/optimizer.yml',
  './include/rtdetr_mot_r50vd.yml',
  './include/tracker.yml',
]



HybridEncoder:
  attn: 'QuantMultiheadAttention'



RTDETRTransformerForMOT:
  attn: 'QuantMultiheadAttention'


train_dataloader: 
  batch_size: 1
  num_workers: 0 # TODO: 4


epoches: 20
# output_dir: ./output/rtdetr_r50vd_lmot_light_isp_det


# online tracking config
RuntimeTrackerBase:
  score_thresh: 0.4 # 0.5
  filter_score_thresh: 0.3 #0.4
  miss_tolerance: 5

tracker:
  mot_or_det: mot_det
  # remap_category: false
  score_thresh: 0.4 # 0.5
  area_threshold: 100 
  visualize: null 
  clip_box: false